interface { name = 'minhaInt',
            methods = {
                foo = {
                args = {
                    { direction = 'in', type = 'double' },
                    { direction = 'in', type = 'double' },
                    { direction = 'out', type = 'string' },
                }}
                }
            }
