interface { name = 'minhaInt',
            methods = {
                foo = { resulttype = 'double',
                args = {
                    { type = 'double' }
                }}
                }
            }
